// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYcc8HhU46V-GTRK62goJoQrQIMSepBe0',
    appId: '1:514367928999:web:dbad07119a1303e54af982',
    messagingSenderId: '514367928999',
    projectId: 'madinaty-bb278',
    authDomain: 'madinaty-bb278.firebaseapp.com',
    storageBucket: 'madinaty-bb278.firebasestorage.app',
    measurementId: 'G-3WSMYL494T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTilfV_-K9HXj0PG8eEH5l1RbsGa4lCr4',
    appId: '1:514367928999:android:2c02011681763eed4af982',
    messagingSenderId: '514367928999',
    projectId: 'madinaty-bb278',
    storageBucket: 'madinaty-bb278.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0iLK7vMLBCn7nm1T2mTNwJbLwGhlC4F4',
    appId: '1:514367928999:ios:c2b8f5cf50291e564af982',
    messagingSenderId: '514367928999',
    projectId: 'madinaty-bb278',
    storageBucket: 'madinaty-bb278.firebasestorage.app',
    androidClientId: '514367928999-ikrik9hi016j2236uq11hkcg4mu4dkp4.apps.googleusercontent.com',
    iosClientId: '514367928999-t46a1eipgdgoj45nr3adig1b7immoafo.apps.googleusercontent.com',
    iosBundleId: 'com.example.madinatyAppIeee2026',
  );


    iosBundleId: 'com.example.madinatyAppIeee2026',
  );
 
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0iLK7vMLBCn7nm1T2mTNwJbLwGhlC4F4',
    appId: '1:514367928999:ios:c2b8f5cf50291e564af982',
    messagingSenderId: '514367928999',
    projectId: 'madinaty-bb278',
    storageBucket: 'madinaty-bb278.firebasestorage.app',
    androidClientId: '514367928999-ikrik9hi016j2236uq11hkcg4mu4dkp4.apps.googleusercontent.com',
    iosClientId: '514367928999-t46a1eipgdgoj45nr3adig1b7immoafo.apps.googleusercontent.com',

    iosBundleId: 'com.example.madinatyAppIeee2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYcc8HhU46V-GTRK62goJoQrQIMSepBe0',
    appId: '1:514367928999:web:c90afb02af99a6584af982',
    messagingSenderId: '514367928999',
    projectId: 'madinaty-bb278',
    authDomain: 'madinaty-bb278.firebaseapp.com',
    storageBucket: 'madinaty-bb278.firebasestorage.app',
    measurementId: 'G-5YD76P70S6',
  );
}
